project:
  type: website

website:
  title: "Feng Cheng"
  navbar:
    background: light
    search: true
    tools:
      - icon: github
        href: https://github.com/fredcheng02
    left:
      - research.qmd
      - blog.qmd
      - links.qmd
      - writings/math_texts.qmd
      - writings/teaching.qmd

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true

editor: visual

