---
title: "Condolences"
description: to my student
date: "5/16/2026"
---

Two days ago, the name of the victim to the random stabbing was released online. Initially I was not too aware of the name; given that the university has so many students, it was very unlikely that I know the victim. At least that was what I thought after learning about the horrendous crime.

But after five minutes, this time looking at the photo and their full name carefully, I suddenly realized that she was definitely one of my Calculus students over the past two years. After scrolling through my personal record, I found that her handwritten signature was indeed on one attendance sheet. That was Fall 2024, my first quarter at UW, and I believe her first undergraduate quarter as well. Back then I was still an inexperienced TA who could not manage the classroom at all.

I still have some memories of her being rather quiet in my class somewhere in the middle of the classroom at MEB, sometimes with her hand on top of her head. A few times I was walking around the classroom, and stopped by asking if she had any questions, and their voice. I also remember her taking the final exam in the large hall at Kane in December; that was probably the last time I ever saw her. Now people are mourning for her at the statue before Kane.

Everything just changed so fast, and I could not imagine a worse last minutes of one's life. I genuinely hope that you, Juniper, can have eternal peace after all that suffering, and I feel genuinely sad that you have lost your precious life at such a young age.