---
title: "Textbooks"
format: html
---

## Math at Undergrad and Grad Level

### Calculus

- Thomas' Calculus
- Stewart's Calculus
- Lax & Terrell - *Calculus* and *Multivariable Calculus with Applications*

### Linear Algebra

- Lay, Lay, & McDonald - *Linear Algebra and Its Applications*
- Trefethen & Bau - *Numerical Linear Algebra*
- Sheldon Axler - *Linear Algebra Done Right*
- Friedberg, Insel, Spence - *Linear Algebra*

### Real and Functional Analysis

- Steven Krantz – *Real Analysis and Foundations*
- Walter B. Rudin - *Principles of Mathematical Analysis*
- Thomas Apostol - *Mathematical Analysis*
- Luigi Ambrosio, Giuseppe Da Prato and Andrea Mennucci - *Introduction to Measure Theory and Integration*
- Donald Cohn - *Measure Theory*
- Vladimir I. Bogachev - *Measure Theory, Vol. 1 and 2*
- Bogachev, Smolyanov - *Real and Functional Analysis*
- Gerald B. Folland - *Real Analysis: Modern Techniques and Their Applications*
- Haïm Brezis - *Functional Analysis, Sobolev Spaces and Partial Differential Equations*
- Barry Simon - *A Comprehensive Course in Analysis, Part 1, 2a, 2b, 3, 4*

### Algebra

- John B. Fraleigh - *A First Course in Abstract Algebra*
- Dummit & Foote - *Abstract Algebra*

### Advanced Undergraduate Probability

- Anirban DasGupta - *Fundamentals of Probability: A First Course*
- Grimmett & Welsh - *Probability: An Introduction*
- Gregory Lawler - *Introduction to Stochastic Processes*
- James Norris - *Markov Chains*

### Graduate Probability

- Grimmett & Stirzaker - *Probability and Random Processes*
- Jean-François Le Gall - *Measure Theory, Probability, and Stochastic Processes*
- Rick Durrett - *Probability: Theory and Examples*
- Patrick Billingsley - *Probability and Measure*
- Richard M. Dudley - *Real Analysis and Probability*
- Olav Kallenberg - *Foundations of Modern Probability*

### Markov Chains on countable state space

- Levin, Peres, & Wilmer - *Markov Chains and Mixing Times*

### Brownian Motion and Stochastic Analysis

- Jean-François Le Gall - Brownian Motion, Martingales, and Stochastic Calculus
- Mörters & Peres - *Brownian Motion*
- Revuz & Yor - *Continuous Martingales and Brownian Motion*
- Karatzas & Shreve - *Brownian Motion and Stochastic Calculus*

### Ergodic Theory

- Patrick Billingsley - *Ergodic Theory and Information*
- Einsiedler & Ward - *Ergodic Theory, with a view towards Number Theory*

### High-Dimensional Probability

- Roman Vershynin - *High-Dimensional Probability: An Introduction with Applications to Data Science*
- Ramon van Handel - Lecture Notes for APC 550: Probability in High Dimension

### Statistics

- A.W. van der Vaart - *Asymptotic Statistics*
- Martin Wainwright - *High-dimensional Statistics: A Non-asymptotic Viewpoint*

### Information Theory

- Cover and Thomas - *Elements of Information Theory*
- Polyanskiy and Wu - *Information Theory: from Coding to Learning*

### Game Theory

- Thomas Ferguson - *A Course in Game Theory*
- Karlin & Peres - *Game Theory, Alive*

## Probability Research Texts

- APC550 High-Dimensional Probability (Ramon van Handel)

- Concentration of Measure Phenomenon (Michel Ledoux)

- Probability in Banach Spaces (Michel Ledoux and Michel Talagrand)

- Concentration Inequalities: a Nonasymptotic Theory of Independence (Stéphane Boucheron, Gábor Lugosi, and Pascal Massart)

- Concentration Inequalities and Model Selection (Saint-Flour 2003, Pascal Massart)

- Random Fields and Geometry (Robert Adler and Jonathan Taylor)

- Spectral Analysis of Large Dimensional Random Matrices (Zhidong Bai and Jack Silverstein)

- Percolation (Geoffrey Grimmett)

- 50 Years of First-Passage Percolation (Antonio Auffinger, Michael Damron, and Jack Hanson)

- Proceedings of Symposia in Applied Mathematics Vol.79: Random Growth Models (AMS Short Course January 2–3, 2017; edited by Michael Damron, Firas Rassoul-Agha, and Timo Seppäläinen)

- Statistical Mechanics of Lattice Systems: a Concrete Mathematical Introduction (Sacha Friedli and Yvan Velenik)

- A Course on Large Deviations with an Introduction to Gibbs Measures (GSM 162; Firas Rassoul-Agha and Timo Seppäläinen)

- Analysis and Geometry of Markov Diffusion Operators (Dominique Bakry, Ivan Gentil, and Michel Ledoux)

- Spectral Analysis of Large Dimensional Random Matrices (Zhidong Bai, Jack Silverstein)

## Alternative proofs of well-known results

- 
